# Generated by Django 3.0.8 on 2020-08-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de tú Pais')),
                ('state', models.CharField(max_length=50, verbose_name='Nombre del Estado')),
                ('country', models.CharField(max_length=50, verbose_name='Capital')),
                ('phone', models.CharField(max_length=15, verbose_name='Número de Tlf.')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
            ],
        ),
    ]
